name: mie451-assignment-ci
dependencies:
  - python=3.6
  - nb_conda
  - pandas=0.23.4
  - pip:
    - rasa-core==0.11.12
    - rasa-core-sdk==0.11.5
    - rasa-nlu==0.13.7
    - sklearn_crfsuite
    - prompt_toolkit